title: OL Engineering Handbook
description: Handbook for Open Learning Engineering

show_downloads: false
google_analytics:

remote_theme: just-the-docs/just-the-docs
markdown: kramdown
plugins:
  - jekyll-feed

liquid:
  error_mode: lax
